on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.34', '5.32', '5.30', '5.28', '5.26' ]
    container:
      image: perl:${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          # Install using cpanm
          cpanm -n -q --skip-satisfied --installdeps .

      - name: Configure code coverage
        if: matrix.perl == '5.34'
        run: |
          # Code coverage setup
          cpanm -n -q --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
          cover -delete
          perl -MDevel::Cover=+ignore,^local/,^t/ t/compile.t
          perl -MDevel::Cover=+ignore,^local/,^t/ t/plugins.t
          perl -MDevel::Cover=+ignore,^local/,^t/ t/engine.t

      - name: Run build script
        run: |
          perl Build.PL && ./Build && ./Build test

      - name: Run tests
        run: |
          - perl -MDevel::Cover t/compile.t
          - perl -MDevel::Cover t/engine.t
          - perl -MDevel::Cover t/plugins.t
          - perl -MDevel::Cover t/util-wrap.t

      - name: Generate code coverage report
        if: matrix.perl == '5.34'
        run: |
          # Code coverage
          cover -report codecovbash

      - uses: codecov/codecov-action@v2
        if: matrix.perl == '5.34'
        with:
          files: ./cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true